[project]
name = "tinynn"
version = "0.0.1"
authors = [{ name = "Mateusz Furga", email = "matfurga@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
  "numpy>=2.0.0,<3.0.0"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

